name: Sync PDFs to Google Drive

on:
  push:
    branches:
      - main
    paths:
      - 'high_school_physics/**/*.pdf'
  workflow_dispatch:

jobs:
  upload-to-gdrive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prep PDFs for Upload
        run: |
          mkdir upload_pdfs
          find high_school_physics -name "*.pdf" -exec cp {} upload_pdfs/ \;

      - name: Upload PDF Files to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          filename: "upload_pdfs/*.pdf"
          overwrite: "true"
